### Create a new user #03-13
Post http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "arlo@arlo.com",
    "password": "arlothepet"
}

### sign in as an existing user
Post http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "arlo@arlo.com",
    "password": "arlothepet"
}

### get the current signed in user
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout


###  
Get http://localhost:3000/auth/2

###
Get http://localhost:3000/auth?email=arlo@arlo.com

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "arlothedog"
}

### Delete a user given id
DELETE http://localhost:3000/auth/4